#ifndef _H_MECRO_H_
#define _H_MECRO_H_
#include <time.h>
#include <fstream>
#include <iostream>
#include <string.h>
#include <algorithm>
#define ANIME_TIME  0.02f	//애니메이션 타임
#define MAX_CHAR_SIZE 5		//전체 캐릭터 사이즈

enum ALL_SCENCE
{
	TITLE_SCENE,	//메인 타이틀 씬
	GAME_SCENE		//게임 씬
};

enum PLAY_STATE
{
	PLAY_NONE,
	PLAY_WIN,
	PLAY_LOSE
};

enum ALL_SIZE
{
	WINDOW_SIZE_X = 1280,
	WINDOW_SIZE_Y = 800,
	TILE_MAP_SIZE = 10,

	MAP_MIDDLE_X = 40,
	MAP_MIDDLE_Y = 70,

	INDEX_EXCEL_SIZE = 49,
	INDEX_PLAYER_CHAR_START = 0,
	INDEX_PLAYER_CHAR_SIZE = 9,
	INDEX_PLAYER_CHAR_END = INDEX_PLAYER_CHAR_START + INDEX_PLAYER_CHAR_SIZE,
	//플레이어블 캐릭터 갯수

	ENEMY_NUM = 1000,

	INDEX_ENEMY_CHAR_START = 0,
	INDEX_ENEMY_CHAR_SIZE = 4,
	INDEX_ENEMY_CHAR_END = INDEX_ENEMY_CHAR_START + INDEX_ENEMY_CHAR_SIZE,
	//적의 갯수

	BOSS_NUM = 10000,

	INDEX_BOSS_CHAR_START = 0,
	INDEX_BOSS_CHAR_SIZE = 6,
	INDEX_BOSS_CHAR_END = INDEX_BOSS_CHAR_START + INDEX_BOSS_CHAR_SIZE,
	//보스의 갯수
};

enum POINT_SIZE
{
	POINT_START,
	POINT_DC_START = POINT_START,	//DC 시작 포인트
	POINT_BIT_SIZE,					//그려줄 비트맵 사이즈
	POINT_BIT_NUM,					//비트맵의 갯수
	POINT_CHAR_MIDDLE,				//중간점
	POINT_END
};

enum CHARACTER_STATE
{
	STATE_START,
	STATE_WAIT = STATE_START,	//대기 상태
	STATE_ATTACK,				//공격 상태
	STATE_MOVE,					//무브 상태
	STATE_VICTORY,				//승리 상태
	STATE_DIE,					//죽음 상태
	STATE_END,					//일반 캐릭터 엔딩
	STATE_RELOAD = STATE_END,	//리로드
	STATE_SET,					//셋팅
	STATE_ALL_END
};

enum CHARACTER_STATS
{
	STATS_START,
	STATS_ATK = STATS_START,	//공격력
	STATS_DEF,					//방어력
	STATS_RANGE,				//범위
	STATS_SPEED,				//자체 속력
	STATS_END
};

enum SKILL_TYPE
{
	SKILL_TYPE_START,
	SKILL_BUF = SKILL_TYPE_START,
	SKILL_DEBUF,
	SKILL_END
};

#endif // !_H_MECRO_H_

